### ISSUE TITLE
Not working on MenuItems

### ISSUE THREAD

**Issue by syonabhisheksingh** [htoomyintnaung/mmtext#1]
I tried this library for App development. It is working on every screens but not working on MenuItems?

Is there any specific flow I need to adopt to do same or am I implementing anything wrong.

Please assist me for the same.

**Comment by syonabhisheksingh** [comment]
it still loading wrong font... #1

**Comment by septemberboy7** [comment]
If you are using Zawgyi. Use mmtext.TEXT_UNICODE for Encoded Text parameter

**Comment by syonabhisheksingh** [comment]
![screenshot_2016-02-24-20-40-17](https://cloud.githubusercontent.com/assets/3416184/13285709/1571521a-db22-11e5-9892-394aea3b9b37.png)
In the attached screenshot there are two arrow, both string are same , but looking different. it looks good on textview but not on menuitem

**Comment by syonabhisheksingh** [comment]
<string name="action_settings">ကၽြႏ္ုပ္္တုိ႔အေၾကာင္း္</string>

this is the string that i am using, and my app works great by using  mmtext.TEXT_ZAWGYI , but this not working on menu items, I added mmtext.prepareActivity(this, mmtext.TEXT_ZAWGYI, true, true); at last line of onCreate.

**Comment by syonabhisheksingh** [comment]
Thanks , it's working now.

**Comment by syon-manish** [comment]
The menu item text is cutting from upper side, can you please have a look on this issue. please look at attached image
![cutting](https://cloud.githubusercontent.com/assets/17473324/13776671/73c4007e-ead1-11e5-91e0-285e36cc356c.png)
