### ISSUE TITLE
Not working for Progress & Alert Dialog 

### ISSUE THREAD

**Issue by syonabhisheksingh** [htoomyintnaung/mmtext#4]
I implemented library firstly I got issue for menu items. Earlier it was not working for the same but after some fixes by author it is working fine.

Somehow, now it is not working for Progress Dialog and Alert Dialog builder.

Please assist me if there is any solution for the same.

Thanks
Abhishek Singh

**Comment by septemberboy7** [comment]
You should create custom views for Dialogs.
